version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        links: 
            - mongodb

    mongodb:
      image: mongo
      ports:
        - "27017:27017"

    mongo-seed:
      build: ./database
      links:
        - mongodb