version: '2'
services:
    web:
      container_name: varpred_flask
      build: .
      ports:
          - "5000:5000"
      volumes:
          - .:/code
      links: 
          - mongodb

    mongodb:
      container_name: mongodb
      build: ./mongodb
      ports:
        - "27017:27017"

    mongo-seed:
      container_name: mongoseed
      build: ./database
      links:
        - mongodb