FROM mongo
COPY variant-37.json variant-37.json
COPY variant-38.json variant-38.json
CMD mongoimport --host mongodb --db varpred --collection variants-37 --type json --file variant-37.json --jsonArray && mongoimport --host mongodb --db varpred --collection variants-38 --type json --file variant-38.json --jsonArray && db.variants-38.createIndex( {'CHROM': 1, 'POS': 1, 'REF': 1, 'ALT': 1} )