FROM mongo
COPY seed-script.sh seed-script.sh
COPY variant-37.json variant-37.json
COPY variant-38.json variant-38.json
#COPY geneinfo.json geneinfo.json
EXPOSE 27017
CMD ["/bin/bash", "seed-script.sh"]